# Generated by Django 3.2 on 2021-04-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(max_length=1000)),
                ('game_log', models.CharField(max_length=10000)),
                ('n_players', models.IntegerField(default=1)),
                ('player_ids', models.CharField(max_length=100)),
                ('scores', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('card1', models.IntegerField(default=-1)),
                ('card2', models.IntegerField(default=-1)),
                ('card3', models.IntegerField(default=-1)),
                ('card4', models.IntegerField(default=-1)),
                ('card5', models.IntegerField(default=-1)),
                ('game_foreign_key', models.ManyToManyField(to='display.Game')),
            ],
        ),
    ]
