# Generated by Django 3.2 on 2021-04-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='used_cards',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
