# Generated by Django 3.2 on 2021-05-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20210427_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='card1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card5',
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default="{'round': 0, 'turn': ''}", max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='cards',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(default='Guesser', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='n_players',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_ids',
            field=models.CharField(max_length=1000),
        ),
    ]
