# Generated by Django 3.2 on 2021-05-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20210502_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='n_players',
            field=models.IntegerField(default=1),
        ),
    ]
