# Generated by Django 3.2 on 2021-05-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_alter_game_n_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_load',
            field=models.CharField(default='()', max_length=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='loading_agent',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
