# Generated by Django 3.2 on 2021-05-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210503_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_load',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
